version: '2'
networks: 
  basic: 

services:
  tlsca.universe.at:
    container_name: tlsca.universe.at
    image: hyperledger/fabric-ca:1.4.4
    command: sh -c 'fabric-ca-server start -d -b tls-ca-admin:tls-ca-adminpw --port 7052'
    environment:
      - FABRIC_CA_SERVER_HOME=/etc/hyperledger/fabric-ca
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CA_NAME=tlsca.universe.at
      - FABRIC_CA_SERVER_CSR_CN=tlsca.universe.at
      - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca/tlsca.universe.at-key.pem
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca/tlsca.universe.at-cert.pem
      - FABRIC_CA_SERVER_DEBUG=true
    volumes:
      - ./fabca/crypto-config/tlsca-server/universe.at:/etc/hyperledger/fabric-ca
    networks:
      - basic
    ports:
      - 7052:7052
